### ISSUE TITLE
Add New Daily Life Problem Solver: Simple Finance Tracker

### ISSUE THREAD

**Issue by sidinsearch** [PreyumKr/DailyLife_Problem_Solvers#23]
Hello, I'd like to contribute to this project for Hacktoberfest 2024 by adding a new problem-solving script: Simple Finance Tracker. My contribution will include:

A Python script that allows users to track daily expenses and incomes.
Basic functionalities like adding, editing, deleting, and viewing expenses/income records.
Generating a summary report of daily, weekly, or monthly expenses.
Updating the README.md file with the usage instructions for the new script.
Please assign this issue to me under Hacktoberfest. Thank you!

**Comment by PreyumKr** [comment]
I have assigned you the task. I am not sure how a script can do the mentioned task for long-term data, but ya, do the work. Let's see what you are up to 😊. Also, star the repo if any of the things available here made your daily life any fun.

**Comment by sidinsearch** [comment]
Hi Preyum Kumar,
I've completed the task you assigned! I've implemented the Simple Finance Tracker, both as a terminal-based and GUI application. It allows users to track their daily expenses and incomes, as well as generate summary reports.

I’ve submitted a pull request for you to review the changes. Let me know your thoughts on it! 😊

**Comment by PreyumKr** [comment]
closing the issue marking it as done.
