### ISSUE TITLE
csv to excel converter|image resizer

### ISSUE THREAD

**Issue by Anuraj-IND** [PreyumKr/DailyLife_Problem_Solvers#28]
as we know in cooperative lives especially of teachers we have so many csv files which needed to be converted in excel so how about i create one?
also i would love to add a image resizer 
url shortner label these for hacktoberfest and assign me these please !

**Comment by PreyumKr** [comment]
Okay assigning. Keep the things light and try mentioning the installation of new packages if they are needed in the project.

**Comment by Anuraj-IND** [comment]
thanks alot! 
ok ill create 
folder with function name 
inside that folder :
.py code file
readme.md file for basic requirements ok?

**Comment by Anuraj-IND** [comment]
done check it out i tested it too! thanks i hope i can update this repo in future too coz its like hub of mini projects

**Comment by Anuraj-IND** [comment]
btw can you add level 2 to it or 1 
@PreyumKr check n add it please

**Comment by PreyumKr** [comment]
What are the levels you are talking about?

**Comment by Anuraj-IND** [comment]
> What are the levels you are talking about?

you can assign level 2 for this since its just easy if person knows how to use git there should be level label / tag too just like hactoberfest tag

**Comment by PreyumKr** [comment]
No idea about that never needed that

**Comment by Anuraj-IND** [comment]
mm ok well now you can close this issue since its completed
