### ISSUE TITLE
codeOFconduct.md file is missing 

### ISSUE THREAD

**Issue by Anuraj-IND** [PreyumKr/DailyLife_Problem_Solvers#29]
codeOFconduct.md is like a rule book of contributors to avoid conflicts while rising issues so let me create that too since you added hacktoberfest label so i guess you would love to allow contributors to work here and your this repo is quiet interesting! i love your idea make sure to add labels while assigning me my issues i want level 2 issue on previous issue and level 1 here and with hacktoberfest on both .
thankyou!
hoping for a quick response

**Comment by PreyumKr** [comment]
Hacktober is only one month and that file is not really important. Just follow the pattern in the readme how the details about the new project should be mentioned. They are ordered in lexical format so take care of that and not much. That file is not needed.

**Comment by PreyumKr** [comment]
Closing this issue

**Comment by Anuraj-IND** [comment]
oki np thanks (just wanted to clear multiple issues labeled as hacktoberfest lol sorry about that)
