### ISSUE TITLE
qr code reader in real time 

### ISSUE THREAD

**Issue by Anuraj-IND** [PreyumKr/DailyLife_Problem_Solvers#32]
hm we dont have qr codes in these days qr code reader are necessary to have and no one really save qr pics and then scan it so how about making a real time qr code scanner ?
lol i just got this idea assign me this with same tags lemme do it lol

**Comment by PreyumKr** [comment]
If you can, then do one that creates its own custom QR, but let's see what you're up to. I'll not merge until you write the main readme properly this time tough

**Comment by Anuraj-IND** [comment]
@PreyumKr done check that and response soo coz theres a badge which i can get if i close issue in 5 mins lol see the pull request

**Comment by Anuraj-IND** [comment]
> If you can, then do one that creates its own custom QR, but let's see what you're up to. I'll not merge until you write the main readme properly this time tough

i did it right this time see 3 single hashes and new generated file is inside project folder @PreyumKr

**Comment by PreyumKr** [comment]
Ya its better than before.

**Comment by Anuraj-IND** [comment]
@PreyumKr  im also in gssoc-ext i wasnt aware this project is there too can you add these two lables to my both pulls itll be helpful for me

**Comment by PreyumKr** [comment]
I am also unaware of what you guys are saying. GSOC has its own projects, right? I don't know about its direct affiliation with this. If they are partnered with Hacktoberfest anyway, then it's okay. I am not involved in GSoC in any way.

**Comment by Anuraj-IND** [comment]
> I am also unaware of what you guys are saying. GSOC has its own projects, right? I don't know about its direct affiliation with this. If they are partnered with Hacktoberfest anyway, then it's okay. I am not involved in GSoC in any way.

its gssoc not gsoc yea seems like u can use this tag means i can contribute to both hacktoberfest and gssoc together

**Comment by PreyumKr** [comment]
Ya I looked at their website and I still don't think this repo has any affiliation to that or is it. They have their projects mentioned on their site.
