### ISSUE TITLE
Text to voice convertor

### ISSUE THREAD

**Issue by Arisha2902** [PreyumKr/DailyLife_Problem_Solvers#33]
I can make a text to voice converter interface , but it will be a web page .

Using html, css and mainly Java Script.
We will text and get pronunciation of that text in any language we choose.

**Comment by PreyumKr** [comment]
Will it be using Openai models offline or some API connection of some sort?

**Comment by Arisha2902** [comment]
API  using js

**Comment by PreyumKr** [comment]
okay. let's see the work. Remember to keep API keys hidden, and instructions on how to create such keys if the user needs to create his/her own API key should be mentioned in the instructions.

**Comment by Arisha2902** [comment]
Okh I will try to mention in the instruction how to make their " api" for this.

**Comment by Arisha2902** [comment]
Sorry I forget that my code is offline using a function of javascript , I forget that it was not using the api .
My apologies if you don't like the offline idea and like the api idea then unassigned it.
Rest I can do it offline.

plz add the tag "gssoc-ext" as well.

**Comment by PreyumKr** [comment]
what's that tag for?

**Comment by Arisha2902** [comment]
since I have registered for  both "hacktoberfest" and "gsssoc 2024" ,although they both are colabirating this year.
But if you add that ,it will be better.

**Comment by PreyumKr** [comment]
Okay closing the issue.
