### ISSUE TITLE
Creating a Qr Code Generator

### ISSUE THREAD

**Issue by Arisha2902** [PreyumKr/DailyLife_Problem_Solvers#36]
I am developing a QR code generator app that allows users to input any text, and the app will generate a corresponding QR code.
 When scanned, the QR code will return the exact text that was initially provided. 
The app will be simple to use and can be integrated into various platforms for easy sharing.

Using html, css and mainly Java Script.

**Comment by PreyumKr** [comment]
Will it create a QR from its own logic or use a prebuilt tool? New, unique QR generators would be nice. I am also thinking of making a QR from scratch, but ya go for it. The basic functionality of QR to text and vice versa conversion, even with readymade modules, are great for some people looking for a fast approach to creating QR.

**Comment by Arisha2902** [comment]
It is using external api to generate Qr

**Comment by PreyumKr** [comment]
okay. When youll push the code i'll look how it works.

**Comment by PreyumKr** [comment]
I dont think gssoc extended is linked with this repo. Its for only hacktoberfest. For GSSoC you should visit their projects that they have floated on their page's project section and contribute on them I guess. Those repos even have their gssoc tag.

**Comment by Arisha2902** [comment]
sir. actually the website is readdy but it is not responsive.
I am having my sessional nowdaya so if you alllow can I upload this on 28.


Uploading labbo - Google Chrome 2024-10-22 09-31-03.mp4…

or I can do is upload the code now then make it responsive on 28

**Comment by PreyumKr** [comment]
Sure whenever you can push the code. That's no problem, I guess.

**Comment by PreyumKr** [comment]
How come this line: <br> `NOTE: If you face any issues with the path of videos while running the tree script or the other two scripts then try moving the working folder closer to the root directory of the drive. It might solve the issue.` <br> went missing from the latest readme in your update I have no idea. But its okay, I cloned and brought it back. Closing this issue.
